# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'scanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 # pod 'CameraFramework', :path => "../CameraFramework/"
pod 'CameraFramework'
  # Pods for scanner

  target 'scannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'scannerUITests' do
    # Pods for testing
  end

end
