# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'checksc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for checksc
pod 'CameraFramework'
  target 'checkscTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'checkscUITests' do
    # Pods for testing
  end

end
